using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;

public class InputManager : MonoBehaviour
{
    private static InputManager _instance;

    public static InputManager Instance {
        get {
            return _instance;
        }
    }

    // reference to input file generated by InputSystem
    private PlayerInput playerInput;

    // Start is called before the first frame update
    void Awake()
    {
        playerInput = new PlayerInput();

        if (_instance != null && _instance != this)
        {
            Destroy(this.gameObject);
        }
        else
        {
            _instance = this;
        }
    }

    private void OnEnable()
    {
        playerInput.Enable();
    }

    private void OnDisable()
    {
        playerInput.Disable();
    }

    public Vector2 GetPlayerFootMovement()
    {
        return playerInput.OnFoot.Movement.ReadValue<Vector2>();
    }

    public Vector2 GetPlayerFootLook()
    {
        return playerInput.OnFoot.Look.ReadValue<Vector2>();
    }

    public bool GetPlayerFootJump()
    {
        return playerInput.OnFoot.Jump.triggered;
    }

    public bool GetPlayerFootSprint()
    {
        return playerInput.OnFoot.Sprint.triggered;
    }

    public bool GetPlayerFootCrouch()
    {
        return playerInput.OnFoot.Crouch.triggered;
    }
}
